# Generated by Django 3.2.7 on 2021-10-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MachineLearning',
            fields=[
                ('MachineLearningId', models.AutoField(primary_key=True, serialize=False)),
                ('TypeOfSheet', models.CharField(choices=[('Balance Sheet', 'Balance Sheet'), ('Profit and Loss', 'Profit and Loss')], max_length=40)),
                ('TrainingDataFileName', models.CharField(max_length=100)),
                ('SheetFileName', models.CharField(max_length=100)),
                ('Output', models.TextField(max_length=100000)),
                ('TrainingDataContent', models.TextField(default='EMPTY', max_length=100000)),
            ],
        ),
    ]
